name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core 3.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build Prise with netcoreapp2.1
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp2.1
    - name: Build Prise with netcoreapp3.0
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp3.0
      
    - name: Test Prise with netcoreapp3.0
      run: dotnet test src/Tests/Prise.Tests.csproj -f netcoreapp3.0
      
    - name: Build Prise.Plugin with netstandard2.0
      run: dotnet build src/Prise.Plugin/Prise.Plugin.csproj --configuration Release -f netstandard2.0  
    - name: Build Prise.Plugin with netstandard2.1
      run: dotnet build src/Prise.Plugin/Prise.Plugin.csproj --configuration Release -f netstandard2.1
      
    - name: Build Prise.AssemblyScanning.Discovery with netstandard2.0
      run: dotnet build src/Prise.AssemblyScanning.Discovery/Prise.AssemblyScanning.Discovery.csproj --configuration Release -f netstandard2.0
